name: Master Build

on:
  push:
    branches: [ CI/CD-Run ]
  pull_request:
    branches: [ CI/CD-Run ]

env:
  CUCUMBER_PUBLISH_TOKEN: '6c7da1c3-fc13-4175-9cd5-94263c8adef5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn install


